name: NPC
author: alvin0319
main: alvin0319\NPC\NPCPlugin
version: 1.0.9
api: 3.0.0

mcpe-protocol: 408

commands:
  npc:
    description: NPC command.
    permission: npc.command

permissions:
  npc.command:
    default: op
    description: Allow to control command npc.